blank_issues_enabled: true
contact_links:
  - name: Support the project on Patreon
    url: https://www.patreon.com/cw/FatihCakir
    about: If this extension helps you, consider supporting its development.
